# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddSprintWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddSprintWidget(object):
    def setupUi(self, AddSprintWidget):
        AddSprintWidget.setObjectName("AddSprintWidget")
        AddSprintWidget.resize(600, 200)
        AddSprintWidget.setMinimumSize(QtCore.QSize(600, 200))
        AddSprintWidget.setMaximumSize(QtCore.QSize(16777215, 200))
        self.AddSprintWidgetVerticalLayout = QtWidgets.QVBoxLayout(AddSprintWidget)
        self.AddSprintWidgetVerticalLayout.setObjectName("AddSprintWidgetVerticalLayout")
        self.nameHorizontalLayout = QtWidgets.QHBoxLayout()
        self.nameHorizontalLayout.setObjectName("nameHorizontalLayout")
        self.nameLabel = QtWidgets.QLabel(AddSprintWidget)
        font = QtGui.QFont()
        font.setFamily("GOST type B")
        font.setPointSize(12)
        self.nameLabel.setFont(font)
        self.nameLabel.setObjectName("nameLabel")
        self.nameHorizontalLayout.addWidget(self.nameLabel)
        self.nameLineEdit = QtWidgets.QLineEdit(AddSprintWidget)
        font = QtGui.QFont()
        font.setFamily("GOST type B")
        font.setPointSize(12)
        self.nameLineEdit.setFont(font)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.nameHorizontalLayout.addWidget(self.nameLineEdit)
        self.AddSprintWidgetVerticalLayout.addLayout(self.nameHorizontalLayout)
        self.dateHorizontalLayout = QtWidgets.QHBoxLayout()
        self.dateHorizontalLayout.setObjectName("dateHorizontalLayout")
        self.startDateGroupBox = QtWidgets.QGroupBox(AddSprintWidget)
        font = QtGui.QFont()
        font.setFamily("GOST type B")
        font.setPointSize(10)
        self.startDateGroupBox.setFont(font)
        self.startDateGroupBox.setObjectName("startDateGroupBox")
        self.startDateGroupBoxHorizontalLayout = QtWidgets.QHBoxLayout(self.startDateGroupBox)
        self.startDateGroupBoxHorizontalLayout.setObjectName("startDateGroupBoxHorizontalLayout")
        self.startDateEdit = QtWidgets.QDateEdit(self.startDateGroupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.startDateEdit.setFont(font)
        self.startDateEdit.setDate(QtCore.QDate(2023, 1, 1))
        self.startDateEdit.setObjectName("startDateEdit")
        self.startDateGroupBoxHorizontalLayout.addWidget(self.startDateEdit)
        self.dateHorizontalLayout.addWidget(self.startDateGroupBox)
        self.endDateGroupBox = QtWidgets.QGroupBox(AddSprintWidget)
        font = QtGui.QFont()
        font.setFamily("GOST type B")
        font.setPointSize(10)
        self.endDateGroupBox.setFont(font)
        self.endDateGroupBox.setObjectName("endDateGroupBox")
        self.endDateGroupBoxHorizontalLayout = QtWidgets.QHBoxLayout(self.endDateGroupBox)
        self.endDateGroupBoxHorizontalLayout.setObjectName("endDateGroupBoxHorizontalLayout")
        self.endDateEdit = QtWidgets.QDateEdit(self.endDateGroupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.endDateEdit.setFont(font)
        self.endDateEdit.setDate(QtCore.QDate(2023, 1, 1))
        self.endDateEdit.setObjectName("endDateEdit")
        self.endDateGroupBoxHorizontalLayout.addWidget(self.endDateEdit)
        self.dateHorizontalLayout.addWidget(self.endDateGroupBox)
        self.AddSprintWidgetVerticalLayout.addLayout(self.dateHorizontalLayout)
        self.createPushButton = QtWidgets.QPushButton(AddSprintWidget)
        font = QtGui.QFont()
        font.setFamily("GOST type B")
        font.setPointSize(10)
        self.createPushButton.setFont(font)
        self.createPushButton.setObjectName("createPushButton")
        self.AddSprintWidgetVerticalLayout.addWidget(self.createPushButton)

        self.retranslateUi(AddSprintWidget)
        QtCore.QMetaObject.connectSlotsByName(AddSprintWidget)

    def retranslateUi(self, AddSprintWidget):
        _translate = QtCore.QCoreApplication.translate
        AddSprintWidget.setWindowTitle(_translate("AddSprintWidget", "Новый спринт"))
        self.nameLabel.setText(_translate("AddSprintWidget", "Название"))
        self.startDateGroupBox.setTitle(_translate("AddSprintWidget", "Начало"))
        self.endDateGroupBox.setTitle(_translate("AddSprintWidget", "Конец"))
        self.createPushButton.setText(_translate("AddSprintWidget", "Создать"))
