# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EditPasswordWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditPasswordWidget(object):
    def setupUi(self, EditPasswordWidget):
        EditPasswordWidget.setObjectName("EditPasswordWidget")
        EditPasswordWidget.resize(450, 200)
        EditPasswordWidget.setMinimumSize(QtCore.QSize(450, 200))
        EditPasswordWidget.setMaximumSize(QtCore.QSize(16777215, 200))
        self.gridLayout = QtWidgets.QGridLayout(EditPasswordWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.passwordCheckLineEdit = QtWidgets.QLineEdit(EditPasswordWidget)
        font = QtGui.QFont()
        font.setFamily("GOST type B")
        font.setPointSize(12)
        self.passwordCheckLineEdit.setFont(font)
        self.passwordCheckLineEdit.setObjectName("passwordCheckLineEdit")
        self.gridLayout.addWidget(self.passwordCheckLineEdit, 2, 1, 1, 1)
        self.oldPasswordLabel = QtWidgets.QLabel(EditPasswordWidget)
        font = QtGui.QFont()
        font.setFamily("GOST type B")
        font.setPointSize(12)
        self.oldPasswordLabel.setFont(font)
        self.oldPasswordLabel.setObjectName("oldPasswordLabel")
        self.gridLayout.addWidget(self.oldPasswordLabel, 0, 0, 1, 1)
        self.newPasswordLineEdit = QtWidgets.QLineEdit(EditPasswordWidget)
        font = QtGui.QFont()
        font.setFamily("GOST type B")
        font.setPointSize(12)
        self.newPasswordLineEdit.setFont(font)
        self.newPasswordLineEdit.setObjectName("newPasswordLineEdit")
        self.gridLayout.addWidget(self.newPasswordLineEdit, 1, 1, 1, 1)
        self.newPasswordLabel = QtWidgets.QLabel(EditPasswordWidget)
        font = QtGui.QFont()
        font.setFamily("GOST type B")
        font.setPointSize(12)
        self.newPasswordLabel.setFont(font)
        self.newPasswordLabel.setObjectName("newPasswordLabel")
        self.gridLayout.addWidget(self.newPasswordLabel, 1, 0, 1, 1)
        self.oldPasswordLineEdit = QtWidgets.QLineEdit(EditPasswordWidget)
        font = QtGui.QFont()
        font.setFamily("GOST type B")
        font.setPointSize(12)
        self.oldPasswordLineEdit.setFont(font)
        self.oldPasswordLineEdit.setObjectName("oldPasswordLineEdit")
        self.gridLayout.addWidget(self.oldPasswordLineEdit, 0, 1, 1, 1)
        self.passwordCheckLabel = QtWidgets.QLabel(EditPasswordWidget)
        font = QtGui.QFont()
        font.setFamily("GOST type B")
        font.setPointSize(12)
        self.passwordCheckLabel.setFont(font)
        self.passwordCheckLabel.setObjectName("passwordCheckLabel")
        self.gridLayout.addWidget(self.passwordCheckLabel, 2, 0, 1, 1)
        self.submitPushButton = QtWidgets.QPushButton(EditPasswordWidget)
        font = QtGui.QFont()
        font.setFamily("GOST type B")
        font.setPointSize(10)
        self.submitPushButton.setFont(font)
        self.submitPushButton.setObjectName("submitPushButton")
        self.gridLayout.addWidget(self.submitPushButton, 3, 0, 1, 1)

        self.retranslateUi(EditPasswordWidget)
        QtCore.QMetaObject.connectSlotsByName(EditPasswordWidget)
        EditPasswordWidget.setTabOrder(self.oldPasswordLineEdit, self.newPasswordLineEdit)
        EditPasswordWidget.setTabOrder(self.newPasswordLineEdit, self.passwordCheckLineEdit)
        EditPasswordWidget.setTabOrder(self.passwordCheckLineEdit, self.submitPushButton)

    def retranslateUi(self, EditPasswordWidget):
        _translate = QtCore.QCoreApplication.translate
        EditPasswordWidget.setWindowTitle(_translate("EditPasswordWidget", "Смена пароля"))
        self.oldPasswordLabel.setText(_translate("EditPasswordWidget", "Старый пароль"))
        self.newPasswordLabel.setText(_translate("EditPasswordWidget", "Новый пароль"))
        self.passwordCheckLabel.setText(_translate("EditPasswordWidget", "Новый еще раз"))
        self.submitPushButton.setText(_translate("EditPasswordWidget", "Принять"))
