# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWidget(object):
    def setupUi(self, LoginWidget):
        LoginWidget.setObjectName("LoginWidget")
        LoginWidget.resize(348, 263)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(LoginWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.headerLabel = QtWidgets.QLabel(LoginWidget)
        font = QtGui.QFont()
        font.setFamily("GOST type B")
        font.setPointSize(20)
        self.headerLabel.setFont(font)
        self.headerLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.headerLabel.setObjectName("headerLabel")
        self.verticalLayout_2.addWidget(self.headerLabel)
        self.loginLabel = QtWidgets.QLabel(LoginWidget)
        font = QtGui.QFont()
        font.setFamily("GOST type B")
        font.setPointSize(12)
        self.loginLabel.setFont(font)
        self.loginLabel.setObjectName("loginLabel")
        self.verticalLayout_2.addWidget(self.loginLabel)
        self.loginLineEdit = QtWidgets.QLineEdit(LoginWidget)
        font = QtGui.QFont()
        font.setFamily("GOST type B")
        font.setPointSize(12)
        self.loginLineEdit.setFont(font)
        self.loginLineEdit.setObjectName("loginLineEdit")
        self.verticalLayout_2.addWidget(self.loginLineEdit)
        self.passwordLabel = QtWidgets.QLabel(LoginWidget)
        font = QtGui.QFont()
        font.setFamily("GOST type B")
        font.setPointSize(12)
        self.passwordLabel.setFont(font)
        self.passwordLabel.setObjectName("passwordLabel")
        self.verticalLayout_2.addWidget(self.passwordLabel)
        self.passwordLineEdit = QtWidgets.QLineEdit(LoginWidget)
        font = QtGui.QFont()
        font.setFamily("GOST type B")
        font.setPointSize(12)
        self.passwordLineEdit.setFont(font)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.verticalLayout_2.addWidget(self.passwordLineEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.loginPushButton = QtWidgets.QPushButton(LoginWidget)
        font = QtGui.QFont()
        font.setFamily("GOST type B")
        font.setPointSize(10)
        self.loginPushButton.setFont(font)
        self.loginPushButton.setObjectName("loginPushButton")
        self.horizontalLayout.addWidget(self.loginPushButton)
        self.signupPushButton = QtWidgets.QPushButton(LoginWidget)
        font = QtGui.QFont()
        font.setFamily("GOST type B")
        font.setPointSize(10)
        self.signupPushButton.setFont(font)
        self.signupPushButton.setObjectName("signupPushButton")
        self.horizontalLayout.addWidget(self.signupPushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_2.setStretch(0, 3)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 2)
        self.verticalLayout_2.setStretch(3, 1)
        self.verticalLayout_2.setStretch(4, 2)
        self.verticalLayout_2.setStretch(5, 1)

        self.retranslateUi(LoginWidget)
        QtCore.QMetaObject.connectSlotsByName(LoginWidget)

    def retranslateUi(self, LoginWidget):
        _translate = QtCore.QCoreApplication.translate
        LoginWidget.setWindowTitle(_translate("LoginWidget", "Авторизация"))
        self.headerLabel.setText(_translate("LoginWidget", "Вы не авторизованы"))
        self.loginLabel.setText(_translate("LoginWidget", "Логин"))
        self.passwordLabel.setText(_translate("LoginWidget", "Пароль"))
        self.loginPushButton.setText(_translate("LoginWidget", "Войти"))
        self.signupPushButton.setText(_translate("LoginWidget", "Регистрация"))
