# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWidget(object):
    def setupUi(self, MainWidget):
        MainWidget.setObjectName("MainWidget")
        MainWidget.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWidget)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(-1, 15, -1, -1)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.nameLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("GOST type B")
        font.setPointSize(14)
        self.nameLabel.setFont(font)
        self.nameLabel.setObjectName("nameLabel")
        self.horizontalLayout.addWidget(self.nameLabel)
        self.newProjectPushButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("GOST type B")
        font.setPointSize(12)
        self.newProjectPushButton.setFont(font)
        self.newProjectPushButton.setObjectName("newProjectPushButton")
        self.horizontalLayout.addWidget(self.newProjectPushButton)
        self.profilePushButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("GOST type B")
        font.setPointSize(12)
        self.profilePushButton.setFont(font)
        self.profilePushButton.setObjectName("profilePushButton")
        self.horizontalLayout.addWidget(self.profilePushButton)
        self.exitPushButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("GOST type B")
        font.setPointSize(12)
        self.exitPushButton.setFont(font)
        self.exitPushButton.setObjectName("exitPushButton")
        self.horizontalLayout.addWidget(self.exitPushButton)
        self.horizontalLayout.setStretch(0, 10)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.horizontalLayout.setStretch(3, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.projectsScrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.projectsScrollArea.setWidgetResizable(True)
        self.projectsScrollArea.setObjectName("projectsScrollArea")
        self.projectsScrollAreaWidgetContents = QtWidgets.QWidget()
        self.projectsScrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 776, 506))
        self.projectsScrollAreaWidgetContents.setObjectName("projectsScrollAreaWidgetContents")
        self.projectsScrollAreaWidgetContentsVerticalLayout = QtWidgets.QVBoxLayout(self.projectsScrollAreaWidgetContents)
        self.projectsScrollAreaWidgetContentsVerticalLayout.setObjectName("projectsScrollAreaWidgetContentsVerticalLayout")
        self.projectsScrollArea.setWidget(self.projectsScrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.projectsScrollArea)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 10)
        MainWidget.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWidget)
        QtCore.QMetaObject.connectSlotsByName(MainWidget)
        MainWidget.setTabOrder(self.newProjectPushButton, self.profilePushButton)
        MainWidget.setTabOrder(self.profilePushButton, self.exitPushButton)

    def retranslateUi(self, MainWidget):
        _translate = QtCore.QCoreApplication.translate
        MainWidget.setWindowTitle(_translate("MainWidget", "Scrum pinboard"))
        self.nameLabel.setText(_translate("MainWidget", "Name"))
        self.newProjectPushButton.setText(_translate("MainWidget", "Новый проект"))
        self.profilePushButton.setText(_translate("MainWidget", "Профиль"))
        self.exitPushButton.setText(_translate("MainWidget", "Выйти"))
