from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_LoginDialogWidget(object):
    def setupUi(self, LoginDialog):
        LoginDialog.setObjectName("LoginDialog")
        LoginDialog.resize(400, 254)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.nameLineEdit = QtWidgets.QLineEdit(LoginDialog)
        self.nameLineEdit.setFont(font)
        self.nameLineEdit.setGeometry(QtCore.QRect(130, 20, 251, 41))
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.nameLabel = QtWidgets.QLabel(LoginDialog)
        self.nameLabel.setGeometry(QtCore.QRect(20, 20, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.nameLabel.setFont(font)
        self.nameLabel.setObjectName("nameLabel")
        self.passwordLabel = QtWidgets.QLabel(LoginDialog)
        self.passwordLabel.setGeometry(QtCore.QRect(20, 80, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.passwordLabel.setFont(font)
        self.passwordLabel.setObjectName("passwordLabel")
        self.passwordLineEdit = QtWidgets.QLineEdit(LoginDialog)
        self.passwordLineEdit.setFont(font)
        self.passwordLineEdit.setGeometry(QtCore.QRect(130, 80, 251, 41))
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.loginPushButton = QtWidgets.QPushButton(LoginDialog)
        self.loginPushButton.setGeometry(QtCore.QRect(22, 140, 361, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.loginPushButton.setFont(font)
        self.loginPushButton.setObjectName("loginPushButton")
        self.SignupPushButton = QtWidgets.QPushButton(LoginDialog)
        self.SignupPushButton.setGeometry(QtCore.QRect(20, 200, 361, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.SignupPushButton.setFont(font)
        self.SignupPushButton.setObjectName("SignupPushButton")

        self.retranslateUi(LoginDialog)
        QtCore.QMetaObject.connectSlotsByName(LoginDialog)

    def retranslateUi(self, LoginDialog):
        _translate = QtCore.QCoreApplication.translate
        LoginDialog.setWindowTitle(_translate("LoginDialog", "Авторизация"))
        self.nameLabel.setText(_translate("LoginDialog", "Name"))
        self.passwordLabel.setText(_translate("LoginDialog", "Password"))
        self.loginPushButton.setText(_translate("LoginDialog", "Login"))
        self.SignupPushButton.setText(_translate("LoginDialog", "Sign up"))
