from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SignUpDialogWidget(object):
    def setupUi(self, SignUpDialog):
        SignUpDialog.setObjectName("SignUpDialog")
        SignUpDialog.resize(400, 256)
        self.nameLabel = QtWidgets.QLabel(SignUpDialog)
        self.nameLabel.setGeometry(QtCore.QRect(20, 20, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.nameLabel.setFont(font)
        self.nameLabel.setObjectName("nameLabel")
        self.nameLineEdit = QtWidgets.QLineEdit(SignUpDialog)
        self.nameLineEdit.setFont(font)
        self.nameLineEdit.setGeometry(QtCore.QRect(130, 20, 251, 41))
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.passwordLabel = QtWidgets.QLabel(SignUpDialog)
        self.passwordLabel.setGeometry(QtCore.QRect(20, 80, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.passwordLabel.setFont(font)
        self.passwordLabel.setObjectName("passwordLabel")
        self.passwordLineEdit = QtWidgets.QLineEdit(SignUpDialog)
        self.passwordLineEdit.setGeometry(QtCore.QRect(130, 80, 251, 41))
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.passwordLineEdit.setFont(font)
        self.SignupPushButton = QtWidgets.QPushButton(SignUpDialog)
        self.SignupPushButton.setGeometry(QtCore.QRect(20, 200, 361, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.SignupPushButton.setFont(font)
        self.SignupPushButton.setObjectName("SignupPushButton")
        self.phoneLabel = QtWidgets.QLabel(SignUpDialog)
        self.phoneLabel.setGeometry(QtCore.QRect(20, 140, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.phoneLabel.setFont(font)
        self.phoneLabel.setObjectName("phoneLabel")
        self.phoneLineEdit = QtWidgets.QLineEdit(SignUpDialog)
        self.phoneLineEdit.setFont(font)
        self.phoneLineEdit.setGeometry(QtCore.QRect(130, 140, 251, 41))
        self.phoneLineEdit.setObjectName("phoneLineEdit")

        self.retranslateUi(SignUpDialog)
        QtCore.QMetaObject.connectSlotsByName(SignUpDialog)

    def retranslateUi(self, SignUpDialog):
        _translate = QtCore.QCoreApplication.translate
        SignUpDialog.setWindowTitle(_translate("SignUpDialog", "Регистрация"))
        self.nameLabel.setText(_translate("SignUpDialog", "Name"))
        self.passwordLabel.setText(_translate("SignUpDialog", "Password"))
        self.SignupPushButton.setText(_translate("SignUpDialog", "Sign up"))
        self.phoneLabel.setText(_translate("SignUpDialog", "Phone"))
