from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(264, 313)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.GraphButton = QtWidgets.QPushButton(self.centralwidget)
        self.GraphButton.setGeometry(QtCore.QRect(20, 260, 121, 28))
        self.GraphButton.setToolTip("")
        self.GraphButton.setObjectName("GraphButton")
        self.RedButton = QtWidgets.QRadioButton(self.centralwidget)
        self.RedButton.setGeometry(QtCore.QRect(40, 80, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.RedButton.setFont(font)
        self.RedButton.setObjectName("RedButton")
        self.YellowButton = QtWidgets.QRadioButton(self.centralwidget)
        self.YellowButton.setGeometry(QtCore.QRect(40, 140, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.YellowButton.setFont(font)
        self.YellowButton.setObjectName("YellowButton")
        self.GreenButton = QtWidgets.QRadioButton(self.centralwidget)
        self.GreenButton.setGeometry(QtCore.QRect(40, 200, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.GreenButton.setFont(font)
        self.GreenButton.setObjectName("GreenButton")
        self.TrafficLightsLabel = QtWidgets.QLabel(self.centralwidget)
        self.TrafficLightsLabel.setGeometry(QtCore.QRect(50, 10, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.TrafficLightsLabel.setFont(font)
        self.TrafficLightsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.TrafficLightsLabel.setObjectName("TrafficLightsLabel")
        self.HelpButton = QtWidgets.QPushButton(self.centralwidget)
        self.HelpButton.setGeometry(QtCore.QRect(150, 260, 93, 28))
        self.HelpButton.setObjectName("HelpButton")
        self.HelpButton.setToolTip(
            "Первый светофор был установлен 10 декабря 1868 года в Лондоне возле \n\
здания Британского парламента. Его изобретатель — Джон Пик Найт — был \n\
специалистом по железнодорожным семафорам.")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 264, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.GraphButton.setText(_translate("MainWindow", "Построить график"))
        self.RedButton.setText(_translate("MainWindow", "Красный"))
        self.YellowButton.setText(_translate("MainWindow", "Желтый"))
        self.GreenButton.setText(_translate("MainWindow", "Зеленый"))
        self.TrafficLightsLabel.setText(_translate("MainWindow", "<span style=\" color:#0055ff;\">Светофор</span>"))
        self.HelpButton.setText(_translate("MainWindow", "Справка"))
