# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddDeveloperWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddDeveloperWidget(object):
    def setupUi(self, AddDeveloperWidget):
        AddDeveloperWidget.setObjectName("AddDeveloperWidget")
        AddDeveloperWidget.resize(300, 300)
        AddDeveloperWidget.setMinimumSize(QtCore.QSize(300, 0))
        self.addDeveloperWidgetVerticalLayout = QtWidgets.QVBoxLayout(AddDeveloperWidget)
        self.addDeveloperWidgetVerticalLayout.setObjectName("addDeveloperWidgetVerticalLayout")
        self.tagGroupBox = QtWidgets.QGroupBox(AddDeveloperWidget)
        font = QtGui.QFont()
        font.setFamily("GOST type B")
        font.setPointSize(10)
        self.tagGroupBox.setFont(font)
        self.tagGroupBox.setObjectName("tagGroupBox")
        self.tagGroupBoxHorizontalLayout = QtWidgets.QHBoxLayout(self.tagGroupBox)
        self.tagGroupBoxHorizontalLayout.setObjectName("tagGroupBoxHorizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.tagGroupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.tagGroupBoxHorizontalLayout.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.tagGroupBox)
        self.pushButton.setObjectName("pushButton")
        self.tagGroupBoxHorizontalLayout.addWidget(self.pushButton)
        self.addDeveloperWidgetVerticalLayout.addWidget(self.tagGroupBox)
        self.developersGroupBox = QtWidgets.QGroupBox(AddDeveloperWidget)
        font = QtGui.QFont()
        font.setFamily("GOST type B")
        font.setPointSize(10)
        self.developersGroupBox.setFont(font)
        self.developersGroupBox.setObjectName("developersGroupBox")
        self.developersGroupBoxVerticalLayout = QtWidgets.QVBoxLayout(self.developersGroupBox)
        self.developersGroupBoxVerticalLayout.setObjectName("developersGroupBoxVerticalLayout")
        self.developersScrollArea = QtWidgets.QScrollArea(self.developersGroupBox)
        self.developersScrollArea.setFrameShape(QtWidgets.QFrame.Panel)
        self.developersScrollArea.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.developersScrollArea.setWidgetResizable(True)
        self.developersScrollArea.setObjectName("developersScrollArea")
        self.developersScrollAreaWidgetContents = QtWidgets.QWidget()
        self.developersScrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 252, 152))
        self.developersScrollAreaWidgetContents.setObjectName("developersScrollAreaWidgetContents")
        self.developersScrollAreaWidgetContentsVerticalLayout = QtWidgets.QVBoxLayout(self.developersScrollAreaWidgetContents)
        self.developersScrollAreaWidgetContentsVerticalLayout.setObjectName("developersScrollAreaWidgetContentsVerticalLayout")
        self.developerLabel = QtWidgets.QLabel(self.developersScrollAreaWidgetContents)
        self.developerLabel.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.developerLabel.setFont(font)
        self.developerLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.developerLabel.setObjectName("developerLabel")
        self.developersScrollAreaWidgetContentsVerticalLayout.addWidget(self.developerLabel)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.developersScrollAreaWidgetContentsVerticalLayout.addItem(spacerItem)
        self.developersScrollArea.setWidget(self.developersScrollAreaWidgetContents)
        self.developersGroupBoxVerticalLayout.addWidget(self.developersScrollArea)
        self.addDeveloperWidgetVerticalLayout.addWidget(self.developersGroupBox)

        self.retranslateUi(AddDeveloperWidget)
        QtCore.QMetaObject.connectSlotsByName(AddDeveloperWidget)

    def retranslateUi(self, AddDeveloperWidget):
        _translate = QtCore.QCoreApplication.translate
        AddDeveloperWidget.setWindowTitle(_translate("AddDeveloperWidget", "Добавить участника"))
        self.tagGroupBox.setTitle(_translate("AddDeveloperWidget", "Тег разработчика"))
        self.pushButton.setText(_translate("AddDeveloperWidget", "Найти"))
        self.developersGroupBox.setTitle(_translate("AddDeveloperWidget", "Разработчики"))
        self.developerLabel.setText(_translate("AddDeveloperWidget", "TAG: Developer"))
