# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddEpicWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddEpicWidget(object):
    def setupUi(self, AddEpicWidget):
        AddEpicWidget.setObjectName("AddEpicWidget")
        AddEpicWidget.resize(500, 150)
        AddEpicWidget.setMinimumSize(QtCore.QSize(500, 150))
        AddEpicWidget.setMaximumSize(QtCore.QSize(16777215, 150))
        self.gridLayout = QtWidgets.QGridLayout(AddEpicWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.nameLabel = QtWidgets.QLabel(AddEpicWidget)
        font = QtGui.QFont()
        font.setFamily("GOST type B")
        font.setPointSize(12)
        self.nameLabel.setFont(font)
        self.nameLabel.setObjectName("nameLabel")
        self.gridLayout.addWidget(self.nameLabel, 0, 0, 1, 1)
        self.priorityComboBox = QtWidgets.QComboBox(AddEpicWidget)
        font = QtGui.QFont()
        font.setFamily("GOST type B")
        font.setPointSize(12)
        self.priorityComboBox.setFont(font)
        self.priorityComboBox.setObjectName("priorityComboBox")
        self.gridLayout.addWidget(self.priorityComboBox, 1, 1, 1, 1)
        self.priorityNameLabel = QtWidgets.QLabel(AddEpicWidget)
        font = QtGui.QFont()
        font.setFamily("GOST type B")
        font.setPointSize(12)
        self.priorityNameLabel.setFont(font)
        self.priorityNameLabel.setObjectName("priorityNameLabel")
        self.gridLayout.addWidget(self.priorityNameLabel, 1, 0, 1, 1)
        self.createPushButton = QtWidgets.QPushButton(AddEpicWidget)
        font = QtGui.QFont()
        font.setFamily("GOST type B")
        font.setPointSize(10)
        self.createPushButton.setFont(font)
        self.createPushButton.setObjectName("createPushButton")
        self.gridLayout.addWidget(self.createPushButton, 2, 0, 1, 1)
        self.nameLineEdit = QtWidgets.QLineEdit(AddEpicWidget)
        font = QtGui.QFont()
        font.setFamily("GOST type B")
        font.setPointSize(12)
        self.nameLineEdit.setFont(font)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.gridLayout.addWidget(self.nameLineEdit, 0, 1, 1, 1)

        self.retranslateUi(AddEpicWidget)
        QtCore.QMetaObject.connectSlotsByName(AddEpicWidget)

    def retranslateUi(self, AddEpicWidget):
        _translate = QtCore.QCoreApplication.translate
        AddEpicWidget.setWindowTitle(_translate("AddEpicWidget", "Новый эпик"))
        self.nameLabel.setText(_translate("AddEpicWidget", "Название"))
        self.priorityNameLabel.setText(_translate("AddEpicWidget", "Приоритет"))
        self.createPushButton.setText(_translate("AddEpicWidget", "Создать"))
