# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddTaskWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddTaskWidget(object):
    def setupUi(self, AddTaskWidget):
        AddTaskWidget.setObjectName("AddTaskWidget")
        AddTaskWidget.resize(600, 150)
        AddTaskWidget.setMinimumSize(QtCore.QSize(600, 150))
        AddTaskWidget.setMaximumSize(QtCore.QSize(16777215, 150))
        self.gridLayout = QtWidgets.QGridLayout(AddTaskWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.nameLabel = QtWidgets.QLabel(AddTaskWidget)
        font = QtGui.QFont()
        font.setFamily("GOST type B")
        font.setPointSize(12)
        self.nameLabel.setFont(font)
        self.nameLabel.setObjectName("nameLabel")
        self.gridLayout.addWidget(self.nameLabel, 0, 0, 1, 1)
        self.nameLineEdit = QtWidgets.QLineEdit(AddTaskWidget)
        font = QtGui.QFont()
        font.setFamily("GOST type B")
        font.setPointSize(12)
        self.nameLineEdit.setFont(font)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.gridLayout.addWidget(self.nameLineEdit, 0, 1, 1, 1)
        self.estimatedHoursLabel = QtWidgets.QLabel(AddTaskWidget)
        font = QtGui.QFont()
        font.setFamily("GOST type B")
        font.setPointSize(12)
        self.estimatedHoursLabel.setFont(font)
        self.estimatedHoursLabel.setObjectName("estimatedHoursLabel")
        self.gridLayout.addWidget(self.estimatedHoursLabel, 1, 0, 1, 1)
        self.estimatedHoursSpinBox = QtWidgets.QSpinBox(AddTaskWidget)
        self.estimatedHoursSpinBox.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("GOST type B")
        font.setPointSize(12)
        self.estimatedHoursSpinBox.setFont(font)
        self.estimatedHoursSpinBox.setMaximum(100)
        self.estimatedHoursSpinBox.setSingleStep(1)
        self.estimatedHoursSpinBox.setObjectName("estimatedHoursSpinBox")
        self.gridLayout.addWidget(self.estimatedHoursSpinBox, 1, 1, 1, 1)
        self.createPushButton = QtWidgets.QPushButton(AddTaskWidget)
        font = QtGui.QFont()
        font.setFamily("GOST type B")
        font.setPointSize(10)
        self.createPushButton.setFont(font)
        self.createPushButton.setObjectName("createPushButton")
        self.gridLayout.addWidget(self.createPushButton, 2, 0, 1, 1)

        self.retranslateUi(AddTaskWidget)
        QtCore.QMetaObject.connectSlotsByName(AddTaskWidget)

    def retranslateUi(self, AddTaskWidget):
        _translate = QtCore.QCoreApplication.translate
        AddTaskWidget.setWindowTitle(_translate("AddTaskWidget", "Новый таск"))
        self.nameLabel.setText(_translate("AddTaskWidget", "Название"))
        self.estimatedHoursLabel.setText(_translate("AddTaskWidget", "Прим. часов на решение"))
        self.createPushButton.setText(_translate("AddTaskWidget", "Создать"))
