# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BacklogWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BacklogWidget(object):
    def setupUi(self, BacklogWidget):
        BacklogWidget.setObjectName("BacklogWidget")
        BacklogWidget.resize(1200, 500)
        BacklogWidget.setMinimumSize(QtCore.QSize(1200, 500))
        self.BacklogWidgetHorizontalLayout = QtWidgets.QHBoxLayout(BacklogWidget)
        self.BacklogWidgetHorizontalLayout.setObjectName("BacklogWidgetHorizontalLayout")
        self.epicsGroupBox = QtWidgets.QGroupBox(BacklogWidget)
        font = QtGui.QFont()
        font.setFamily("GOST type B")
        font.setPointSize(12)
        self.epicsGroupBox.setFont(font)
        self.epicsGroupBox.setObjectName("epicsGroupBox")
        self.epicsGroupBoxVerticalLayout = QtWidgets.QVBoxLayout(self.epicsGroupBox)
        self.epicsGroupBoxVerticalLayout.setObjectName("epicsGroupBoxVerticalLayout")
        self.epicsTableWidget = QtWidgets.QTableWidget(self.epicsGroupBox)
        self.epicsTableWidget.setObjectName("epicsTableWidget")
        self.epicsTableWidget.setColumnCount(0)
        self.epicsTableWidget.setRowCount(0)
        self.epicsGroupBoxVerticalLayout.addWidget(self.epicsTableWidget)
        self.BacklogWidgetHorizontalLayout.addWidget(self.epicsGroupBox)
        self.storiesGroupBox = QtWidgets.QGroupBox(BacklogWidget)
        font = QtGui.QFont()
        font.setFamily("GOST type B")
        font.setPointSize(12)
        self.storiesGroupBox.setFont(font)
        self.storiesGroupBox.setObjectName("storiesGroupBox")
        self.storiesGroupBoxVerticalLayout = QtWidgets.QVBoxLayout(self.storiesGroupBox)
        self.storiesGroupBoxVerticalLayout.setObjectName("storiesGroupBoxVerticalLayout")
        self.storiesTableWidget = QtWidgets.QTableWidget(self.storiesGroupBox)
        self.storiesTableWidget.setObjectName("storiesTableWidget")
        self.storiesTableWidget.setColumnCount(0)
        self.storiesTableWidget.setRowCount(0)
        self.storiesGroupBoxVerticalLayout.addWidget(self.storiesTableWidget)
        self.BacklogWidgetHorizontalLayout.addWidget(self.storiesGroupBox)
        self.tasksGroupBox = QtWidgets.QGroupBox(BacklogWidget)
        font = QtGui.QFont()
        font.setFamily("GOST type B")
        font.setPointSize(12)
        self.tasksGroupBox.setFont(font)
        self.tasksGroupBox.setObjectName("tasksGroupBox")
        self.tasksGroupBoxVerticalLayout = QtWidgets.QVBoxLayout(self.tasksGroupBox)
        self.tasksGroupBoxVerticalLayout.setObjectName("tasksGroupBoxVerticalLayout")
        self.tasksTableWidget = QtWidgets.QTableWidget(self.tasksGroupBox)
        self.tasksTableWidget.setObjectName("tasksTableWidget")
        self.tasksTableWidget.setColumnCount(0)
        self.tasksTableWidget.setRowCount(0)
        self.tasksGroupBoxVerticalLayout.addWidget(self.tasksTableWidget)
        self.BacklogWidgetHorizontalLayout.addWidget(self.tasksGroupBox)

        self.retranslateUi(BacklogWidget)
        QtCore.QMetaObject.connectSlotsByName(BacklogWidget)

    def retranslateUi(self, BacklogWidget):
        _translate = QtCore.QCoreApplication.translate
        BacklogWidget.setWindowTitle(_translate("BacklogWidget", "Backlog"))
        self.epicsGroupBox.setTitle(_translate("BacklogWidget", "Эпики"))
        self.storiesGroupBox.setTitle(_translate("BacklogWidget", "Стори"))
        self.tasksGroupBox.setTitle(_translate("BacklogWidget", "Таски"))
