# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWidget — копия.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWidget(object):
    def setupUi(self, MainWidget):
        MainWidget.setObjectName("MainWidget")
        MainWidget.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWidget)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.nameLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("GOST type B")
        font.setPointSize(14)
        self.nameLabel.setFont(font)
        self.nameLabel.setObjectName("nameLabel")
        self.horizontalLayout.addWidget(self.nameLabel)
        self.newProjectPushButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("GOST type B")
        font.setPointSize(12)
        self.newProjectPushButton.setFont(font)
        self.newProjectPushButton.setObjectName("newProjectPushButton")
        self.horizontalLayout.addWidget(self.newProjectPushButton)
        self.profilePushButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("GOST type B")
        font.setPointSize(12)
        self.profilePushButton.setFont(font)
        self.profilePushButton.setObjectName("profilePushButton")
        self.horizontalLayout.addWidget(self.profilePushButton)
        self.exitPushButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("GOST type B")
        font.setPointSize(12)
        self.exitPushButton.setFont(font)
        self.exitPushButton.setObjectName("exitPushButton")
        self.horizontalLayout.addWidget(self.exitPushButton)
        self.horizontalLayout.setStretch(0, 10)
        self.horizontalLayout.setStretch(2, 1)
        self.horizontalLayout.setStretch(3, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.projectsFrame = QtWidgets.QFrame(self.centralwidget)
        self.projectsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.projectsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.projectsFrame.setObjectName("projectsFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.projectsFrame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")





        self.projectFrame = QtWidgets.QFrame(self.projectsFrame)
        self.projectFrame.setMinimumSize(QtCore.QSize(0, 100))
        self.projectFrame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.projectFrame.setFrameShape(QtWidgets.QFrame.Panel)
        self.projectFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.projectFrame.setObjectName("projectFrame")
        self.projectFrameHorizontalLayout = QtWidgets.QHBoxLayout(self.projectFrame)
        self.projectFrameHorizontalLayout.setObjectName("projectFrameHorizontalLayout")
        
        self.projectCreatorGroupBox = QtWidgets.QGroupBox(self.projectFrame)
        font = QtGui.QFont()
        font.setFamily("GOST type B")
        font.setPointSize(10)
        self.projectCreatorGroupBox.setFont(font)
        self.projectCreatorGroupBox.setObjectName("projectCreatorGroupBox")
        self.projectCreatorGroupBoxVerticalLayout = QtWidgets.QVBoxLayout(self.projectCreatorGroupBox)
        self.projectCreatorGroupBoxVerticalLayout.setObjectName("projectCreatorGroupBoxVerticalLayout")
        
        self.projectCreatorLabel = QtWidgets.QLabel(self.projectCreatorGroupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.projectCreatorLabel.setFont(font)
        self.projectCreatorLabel.setObjectName("projectCreatorLabel")
        self.projectCreatorGroupBoxVerticalLayout.addWidget(self.projectCreatorLabel)
        self.projectFrameHorizontalLayout.addWidget(self.projectCreatorGroupBox)
        
        self.projectNameGroupBox = QtWidgets.QGroupBox(self.projectFrame)
        font = QtGui.QFont()
        font.setFamily("GOST type B")
        font.setPointSize(10)
        self.projectNameGroupBox.setFont(font)
        self.projectNameGroupBox.setObjectName("projectNameGroupBox")
        self.projectNameGroupBoxVerticalLayout = QtWidgets.QVBoxLayout(self.projectNameGroupBox)
        self.projectNameGroupBoxVerticalLayout.setObjectName("projectNameGroupBoxVerticalLayout")
        
        self.projectNameLabel = QtWidgets.QLabel(self.projectNameGroupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.projectNameLabel.setFont(font)
        self.projectNameLabel.setObjectName("projectNameLabel")
        self.projectNameGroupBoxVerticalLayout.addWidget(self.projectNameLabel)
        self.projectFrameHorizontalLayout.addWidget(self.projectNameGroupBox)
        
        self.projectOpenVerticalLayout = QtWidgets.QVBoxLayout()
        self.projectOpenVerticalLayout.setObjectName("projectOpenVerticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.projectOpenVerticalLayout.addItem(spacerItem)
        
        self.buttonsHorizontalLayout = QtWidgets.QHBoxLayout()
        self.buttonsHorizontalLayout.setObjectName("buttonsHorizontalLayout")
        self.projectOpenPushButton = QtWidgets.QPushButton(self.projectFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.projectOpenPushButton.sizePolicy().hasHeightForWidth())
        self.projectOpenPushButton.setSizePolicy(sizePolicy)
        self.projectOpenPushButton.setMinimumSize(QtCore.QSize(0, 65))
        self.projectOpenPushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("GOST type B")
        font.setPointSize(12)
        self.projectOpenPushButton.setFont(font)
        self.projectOpenPushButton.setObjectName("projectOpenPushButton")
        self.buttonsHorizontalLayout.addWidget(self.projectOpenPushButton)
        self.projectRemovePushButton = QtWidgets.QPushButton(self.projectFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.projectRemovePushButton.sizePolicy().hasHeightForWidth())
        self.projectRemovePushButton.setSizePolicy(sizePolicy)
        self.projectRemovePushButton.setMinimumSize(QtCore.QSize(0, 65))
        self.projectRemovePushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("GOST type B")
        font.setPointSize(12)
        self.projectRemovePushButton.setFont(font)
        self.projectRemovePushButton.setObjectName("projectRemovePushButton")
        self.buttonsHorizontalLayout.addWidget(self.projectRemovePushButton)
        
        self.projectOpenVerticalLayout.addLayout(self.buttonsHorizontalLayout)
        self.projectFrameHorizontalLayout.addLayout(self.projectOpenVerticalLayout)
        
        self.projectFrameHorizontalLayout.setStretch(0, 2)
        self.projectFrameHorizontalLayout.setStretch(1, 3)





        self.verticalLayout_3.addWidget(self.projectFrame)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.projectsFrame)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 15)
        MainWidget.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWidget)
        QtCore.QMetaObject.connectSlotsByName(MainWidget)
        MainWidget.setTabOrder(self.newProjectPushButton, self.profilePushButton)
        MainWidget.setTabOrder(self.profilePushButton, self.exitPushButton)

    def retranslateUi(self, MainWidget):
        _translate = QtCore.QCoreApplication.translate
        MainWidget.setWindowTitle(_translate("MainWidget", "Scrum pinboard"))
        self.nameLabel.setText(_translate("MainWidget", "Name"))
        self.newProjectPushButton.setText(_translate("MainWidget", "Новый проект"))
        self.profilePushButton.setText(_translate("MainWidget", "Профиль"))
        self.exitPushButton.setText(_translate("MainWidget", "Выйти"))
        self.projectCreatorGroupBox.setTitle(_translate("MainWidget", "Создатель"))
        self.projectCreatorLabel.setText(_translate("MainWidget", "Creator"))
        self.projectNameGroupBox.setTitle(_translate("MainWidget", "Название"))
        self.projectNameLabel.setText(_translate("MainWidget", "Name"))
        self.projectOpenPushButton.setText(_translate("MainWidget", "Открыть"))
        self.projectRemovePushButton.setText(_translate("MainWidget", "Удалить"))
