# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ProfileWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 294)
        self.nameLabel = QtWidgets.QLabel(Dialog)
        self.nameLabel.setGeometry(QtCore.QRect(30, 10, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.nameLabel.setFont(font)
        self.nameLabel.setObjectName("nameLabel")
        self.contractsTableWidget = QtWidgets.QTableWidget(Dialog)
        self.contractsTableWidget.setGeometry(QtCore.QRect(20, 90, 361, 151))
        self.contractsTableWidget.setObjectName("contractsTableWidget")
        self.contractsTableWidget.setColumnCount(0)
        self.contractsTableWidget.setRowCount(0)
        self.passwordLabel = QtWidgets.QLabel(Dialog)
        self.passwordLabel.setGeometry(QtCore.QRect(30, 50, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.passwordLabel.setFont(font)
        self.passwordLabel.setObjectName("passwordLabel")
        self.namePushButton = QtWidgets.QPushButton(Dialog)
        self.namePushButton.setGeometry(QtCore.QRect(290, 10, 93, 31))
        self.namePushButton.setObjectName("namePushButton")
        self.passwordPushButton = QtWidgets.QPushButton(Dialog)
        self.passwordPushButton.setGeometry(QtCore.QRect(290, 50, 93, 31))
        self.passwordPushButton.setObjectName("passwordPushButton")
        self.exitPushButton = QtWidgets.QPushButton(Dialog)
        self.exitPushButton.setGeometry(QtCore.QRect(290, 250, 93, 31))
        self.exitPushButton.setObjectName("exitPushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.nameLabel.setText(_translate("Dialog", "Name"))
        self.passwordLabel.setText(_translate("Dialog", "Password"))
        self.namePushButton.setText(_translate("Dialog", "Изменить"))
        self.passwordPushButton.setText(_translate("Dialog", "Изменить"))
        self.exitPushButton.setText(_translate("Dialog", "Выйти"))
