from PyQt5 import QtCore, QtGui, QtWidgets

class ProjectElement:
    def __init__(self, index, projectName, ownerName, isOwner, projectsFrame, openLambda, removeLambda):
        index = str(index)

        self.projectFrame = QtWidgets.QFrame(projectsFrame)
        self.projectFrame.setMinimumSize(QtCore.QSize(0, 100))
        self.projectFrame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.projectFrame.setFrameShape(QtWidgets.QFrame.Panel)
        self.projectFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.projectFrame.setObjectName("projectFrame_" + index)
        self.projectFrameHorizontalLayout = QtWidgets.QHBoxLayout(self.projectFrame)
        self.projectFrameHorizontalLayout.setObjectName("projectFrameHorizontalLayout_" + index)

        self.projectCreatorGroupBox = QtWidgets.QGroupBox(self.projectFrame)
        font = QtGui.QFont()
        font.setFamily("GOST type B")
        font.setPointSize(10)
        self.projectCreatorGroupBox.setFont(font)
        self.projectCreatorGroupBox.setObjectName("projectCreatorGroupBox_" + index)
        self.projectCreatorGroupBoxVerticalLayout = QtWidgets.QVBoxLayout(self.projectCreatorGroupBox)
        self.projectCreatorGroupBoxVerticalLayout.setObjectName("projectCreatorGroupBoxVerticalLayout_" + index)
        
        self.projectCreatorLabel = QtWidgets.QLabel(self.projectCreatorGroupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        if isOwner:
            font.setBold(True)
        self.projectCreatorLabel.setFont(font)
        self.projectCreatorLabel.setObjectName("projectCreatorLabel_" + index)
        self.projectCreatorGroupBoxVerticalLayout.addWidget(self.projectCreatorLabel)
        self.projectFrameHorizontalLayout.addWidget(self.projectCreatorGroupBox)

        self.projectNameGroupBox = QtWidgets.QGroupBox(self.projectFrame)
        font = QtGui.QFont()
        font.setFamily("GOST type B")
        font.setPointSize(10)
        self.projectNameGroupBox.setFont(font)
        self.projectNameGroupBox.setObjectName("projectNameGroupBox_" + index)
        self.projectNameGroupBoxVerticalLayout = QtWidgets.QVBoxLayout(self.projectNameGroupBox)
        self.projectNameGroupBoxVerticalLayout.setObjectName("projectNameGroupBoxVerticalLayout_" + index)

        self.projectNameLabel = QtWidgets.QLabel(self.projectNameGroupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.projectNameLabel.setFont(font)
        self.projectNameLabel.setObjectName("projectNameLabel_" + index)
        self.projectNameGroupBoxVerticalLayout.addWidget(self.projectNameLabel)
        self.projectFrameHorizontalLayout.addWidget(self.projectNameGroupBox)

        self.projectOpenVerticalLayout = QtWidgets.QVBoxLayout()
        self.projectOpenVerticalLayout.setObjectName("projectButtonsVerticalLayout_" + index)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.projectOpenVerticalLayout.addItem(spacerItem)

        self.buttonsHorizontalLayout = QtWidgets.QHBoxLayout()
        self.buttonsHorizontalLayout.setObjectName("buttonsHorizontalLayout_" + index)

        self.projectOpenPushButton = QtWidgets.QPushButton(self.projectFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.projectOpenPushButton.sizePolicy().hasHeightForWidth())
        self.projectOpenPushButton.setSizePolicy(sizePolicy)
        self.projectOpenPushButton.setMinimumSize(QtCore.QSize(0, 65))
        self.projectOpenPushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("GOST type B")
        font.setPointSize(12)
        self.projectOpenPushButton.setFont(font)
        self.projectOpenPushButton.setObjectName("projectOpenPushButton_" + index)
        self.buttonsHorizontalLayout.addWidget(self.projectOpenPushButton)

        self.projectRemovePushButton = QtWidgets.QPushButton(self.projectFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.projectRemovePushButton.sizePolicy().hasHeightForWidth())
        self.projectRemovePushButton.setSizePolicy(sizePolicy)
        self.projectRemovePushButton.setMinimumSize(QtCore.QSize(0, 65))
        self.projectRemovePushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("GOST type B")
        font.setPointSize(12)
        self.projectRemovePushButton.setFont(font)
        self.projectRemovePushButton.setObjectName("projectRemovePushButton_" + index)
        self.buttonsHorizontalLayout.addWidget(self.projectRemovePushButton)
        
        self.projectOpenVerticalLayout.addLayout(self.buttonsHorizontalLayout)
        self.projectFrameHorizontalLayout.addLayout(self.projectOpenVerticalLayout)
        
        self.projectFrameHorizontalLayout.setStretch(0, 2)
        self.projectFrameHorizontalLayout.setStretch(1, 3)

        # self.projectOpenPushButton = QtWidgets.QPushButton(self.projectFrame)
        # sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        # sizePolicy.setHorizontalStretch(0)
        # sizePolicy.setVerticalStretch(0)
        # sizePolicy.setHeightForWidth(self.projectOpenPushButton.sizePolicy().hasHeightForWidth())
        # self.projectOpenPushButton.setSizePolicy(sizePolicy)
        # self.projectOpenPushButton.setMaximumSize(QtCore.QSize(16777215, 65))
        # self.projectOpenPushButton.setMinimumSize(QtCore.QSize(0, 65))
        # font = QtGui.QFont()
        # font.setFamily("GOST type B")
        # font.setPointSize(12)
        # self.projectOpenPushButton.setFont(font)
        # self.projectOpenPushButton.setObjectName("projectOpenPushButton_" + index)
        # self.projectOpenVerticalLayout.addWidget(self.projectOpenPushButton)

        # self.projectFrameHorizontalLayout.addLayout(self.projectOpenVerticalLayout)

        # self.projectFrameHorizontalLayout.setStretch(0, 3)
        # self.projectFrameHorizontalLayout.setStretch(1, 6)
        # self.projectFrameHorizontalLayout.setStretch(2, 1)

        _translate = QtCore.QCoreApplication.translate
        self.projectCreatorGroupBox.setTitle(_translate("MainWidget", "Создатель"))
        self.projectCreatorLabel.setText(_translate("MainWidget", ownerName))
        self.projectNameGroupBox.setTitle(_translate("MainWidget", "Название"))
        self.projectNameLabel.setText(_translate("MainWidget", projectName))
        self.projectOpenPushButton.setText(_translate("MainWidget", "Открыть"))
        self.projectRemovePushButton.setText(_translate("MainWidget", "Удалить" if isOwner else "Выйти"))

        self.projectOpenPushButton.clicked.connect(openLambda)
        self.projectRemovePushButton.clicked.connect(removeLambda)

    def SetElement(self, verticalLayout):
        verticalLayout.addWidget(self.projectFrame)